"""fix_customer

Revision ID: 6a5ef7fb4e49
Revises: 5cf6d179c6d0
Create Date: 2025-11-27 19:04:17.811146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5ef7fb4e49'
down_revision: Union[str, Sequence[str], None] = '5cf6d179c6d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customers_email_key'), 'customers', type_='unique')
    op.create_index('uq_customer_active', 'customers', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_customer_active', table_name='customers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('customers_email_key'), 'customers', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
